### PR TITLE
fix: BondV2 fee

### PR DESCRIPTION
**Pull request by bejaxer**

### CODE REVIEW

**Comment by michaelnguyen102** [comment]
@bejaxer please attach the report/screenshot from running the test script to make sure test cases didn't fail with your new code.

**Comment by bejaxer** [comment]
Test2
Test1

**Review by michaelnguyen102 — APPROVED** [review]

**Comment by michaelnguyen102** [comment]
image
Test result for func updateFeeWeights is passed!

**Comment by michaelnguyen102** [comment]
[Customizable Bond v2](https://trello.com/c/rCjPnWEf/137-customizable-bond-v2)

**Pull request merged**
